jadwal/urls.py
from django.urls import path

from . import views

app_name = 'jadwal'

urlpatterns = [
    path('', views.daftar, name='daftar'),
    path('buat', views.buat, name='buat'),
    path('del/<int:id>', views.delete, name='del'),
]

my_page/urls.py
from django.urls import path

from . import views

app_name = 'my_page'

urlpatterns = [
    path('', views.front_page, name='front_page'),
    path('about_me', views.about_me, name='about_me'),
    path('skill', views.skill, name='skill'),
    path('experiment', views.experiment, name='experiment'),
    path('contacts', views.contacts, name='contacts'),
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_page.urls')),
    path('jadwal/', include('jadwal.urls')),
]

jadwal/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateField()
    time = models.TimeField()
    place = models.CharField(max_length=200)
    category = models.CharField(max_length=200)

my_page/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms
from .models import Jadwal
from datetime import date

TEXT_ATTRS = {
        'size': 50,
        'style': 'font-family: montserrat; border-radius: 20px; height: 20px; padding: 5px'
    }

class JadwalForm(forms.Form):
    name = forms.CharField(label='Nama Kegiatan', max_length=200, widget=forms.TextInput(attrs=TEXT_ATTRS))
    date = forms.DateField(label='Tanggal', widget=forms.DateInput(attrs={'type': 'date', 'min':date.today(), 'style':'border-radius: 20px; padding: 5px'}))
    time = forms.TimeField(label='Jam', widget=forms.TimeInput(attrs={'type':'time', 'style':'border-radius: 20px; padding: 5px'}))
    place = forms.CharField(label='Tempat', max_length=200, widget=forms.TextInput(attrs=TEXT_ATTRS))
    category = forms.CharField(label='Kategori', max_length=200, widget=forms.TextInput(attrs=TEXT_ATTRS))

jadwal/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import JadwalForm
from .models import Jadwal

DAYS = [
        'Senin',
        'Selasa',
        'Rabu',
        'Kamis',
        'Jumat',
        'Sabtu',
        'Minggu'
        ]
# Create your views here.
def daftar(request):
    jadwals = Jadwal.objects.order_by('date')
    for jadwal in jadwals:
        jadwal.day = DAYS[jadwal.date.weekday()]
    return render(request, 'jadwal/base.html', { 'title': 'jadwal', 'jadwals': jadwals})

def buat(request):
    if request.method == 'POST':
        form = JadwalForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            category = form.cleaned_data['category']
            place = form.cleaned_data['place']

            jadwal = Jadwal(name=name, date=date, time=time, place=place, category=category)
            jadwal.save()

            return HttpResponseRedirect(reverse('jadwal:daftar'))

    else:
        form = JadwalForm()
    return render(request, 'jadwal/buat.html', {'form': form})

def delete(request, id):
    Jadwal.objects.get(pk=id).delete()
    return HttpResponseRedirect(reverse('jadwal:daftar'))

my_page/views.py
from django.shortcuts import render

# Create your views here.
def front_page(request):
    return render(request, 'my_page/front_page.html', {'title':'Naufal'})

def about_me(request):
    return render(request, 'my_page/about_me.html', {'title': 'Naufal'})

def skill(request):
    return render(request, 'my_page/skill.html', {'title': 'Naufal'})

def experiment(request):
    return render(request, 'my_page/experiment.html', {'title': 'Experimental Works'})

def contacts(request):
    return render(request, 'my_page/contacts.html', {'title': 'Find ME'})

jadwal/templates/jadwal/base.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<script src="https://kit.fontawesome.com/058171b902.js" crossorigin="anonymous"></script>
<link href="{% static 'my_page/css/home.css' %}" type="text/css" rel="stylesheet" >
<link href="{% static 'jadwal/css/jadwal.css' %}" type="text/css" rel="stylesheet" >
{% endblock style %}

{% block content %}
  <nav><ul>
      <li><a href="{% url 'my_page:front_page' %}">HOME</a></li>
  </ul></nav>
  {% block view %}
    <section>
      <table>
	<tbody>
	  <tr>
	    <th>NAMA KEGIATAN</th>
	    <th>HARI</th>
	    <th>TANGGAL</th>
	    <th>JAM</th>
	    <th>TEMPAT KEGIATAN</th>
	    <th>NAMA KATEGORI</th>
	    <th>HAPUS</th>
	  </tr>
      {% if jadwals %}
	{% for jadwal in jadwals %}
	  <tr>
	    <td>{{ jadwal.name }}</td>
	    <td>{{ jadwal.day }}</td>
	    <td>{{ jadwal.date }}</td>
	    <td>{{ jadwal.time }}</td>
	    <td>{{ jadwal.place }}</td>
	    <td>{{ jadwal.category }}</td>
	    <td><button class="button-link"><a href="{% url 'jadwal:del' jadwal.id %}"><i class="far fa-times-circle"></i></a></button></td>
	  </tr>
	{% endfor %}
      {% else %}
	<tr>
	  <td colspan="7"><h1>You don't have any schedule yet</h1></td>
	</tr>
      {% endif %}
	</tbody>
      </table>
      <button class="button-link"><a href="{% url 'jadwal:buat' %}">tambah jadwal</a></button>
    </section>
  {% endblock view %}
{% endblock content %}

jadwal/templates/jadwal/buat.html
{% extends 'jadwal/base.html' %}

{% block view %}
  <form style="background-color: white; margin: auto; margin-top: 70px; font-family: 'montserrat'; padding: 20px; width: 50%; " action="{% url 'jadwal:buat' %}" method="POST">
    {% csrf_token %}
    {% for fields in form %}
      <div style="margin: 20px 0px">
	<div>
	{{ fields.errors }}
	</div>
	<div style="margin: 5px">
	{{ fields.label_tag }}<br>
	{{ fields }}
	</div>
      </div>
    {% endfor %}
    <div>
      <input style="padding: 10px; text-decoration: none; font-family: montserrat; background-color: #00adb5; border: none; border-radius:20px; color: white" type="submit">
    </div>
  </form>
{% endblock view %}

my_page/templates/my_page/about_me.html
{% extends 'my_page/base.html' %}
{% load static %}

{% block views %}
  <section id="about-me">
    <h1>ABOUT ME</h1>
    <div class="middle">
      <img src="{% static 'my_page/image/me.jpg' %}">
      <p>A CS Student with a great curiosity and spirit to learn everything</p>
    </div>
  </section>
{% endblock views %}

my_page/templates/my_page/base.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <script src="https://kit.fontawesome.com/058171b902.js" crossorigin="anonymous"></script>
  <link href="{% static 'my_page/css/home.css' %}" type="text/css" rel="stylesheet">
{% endblock style %}

{% block content %}
  <nav><ul>
      <li><a href="{% url 'my_page:about_me' %}">ABOUT ME</a></li>
      <li><a href="{% url 'my_page:skill' %}">SKILL</a></li>
      <li><a href="{% url 'my_page:experiment' %}">EXPERIMENT</a></li>
      <li><a href="{% url 'jadwal:daftar' %}">JADWAL</a></li>
      <li><a href="{% url 'my_page:contacts' %}">CONTACTS</a></li>
  </ul></nav>
  {% block views %}
    <h1>this is my page base html</h1>
  {% endblock views %}
{% endblock content %}

my_page/templates/my_page/contacts.html
{% extends 'my_page/base.html' %}
{% load static %}

{% block views %}
  <section id="contacts">
    <h1>CONTACTS</h1>
    <ul>
      <li><i class="fas fa-envelope"></i></li>
      <li><a style="text-decoration: none; color: #eee;" href="https://gitlab.com/naufalauddin"><i class="fab fa-gitlab"></i></a></li>
    </ul>
  </section>
{% endblock views %}

my_page/templates/my_page/experiment.html
{% extends 'my_page/base.html' %}
{% load static %}

{% block views %}
  <section id="experiment">
    <h1>EXPERIMENT TAB</h1>
    <p>This is my section for experimental webkit or other frontend experiment.</p>
  </section>
  <div class="section-break"></div>
  <section id="coming-soon" class="exp">
    <h1>COMING SOON...</h1>
  </section>
{% endblock views %}

my_page/templates/my_page/front_page.html
{% extends 'my_page/base.html' %}
{% load static %}

{% block views %}
  <section id="front-page">
    <div class="back-blur"></div>
    <h1>HELLO,<br>I'M NAUFAL</h1>
  </section>
{% endblock views %}

my_page/templates/my_page/skill.html
{% extends 'my_page/base.html' %}
{% load static %}

{% block views %}
  <section id="skill">
    <h1>SKILL</h1>
    <div class="skills-block">
      <i class="fab fa-python" style="font-size: 48px; margin-right: 20px;"></i><div class="skill-container"><div id="python" class="skills" style="width: 90%;"></div></div><br>
      <i class="fab fa-java" style="font-size: 48px; margin-right: 20px;"></i><div class="skill-container"><div id="python" class="skills"></div></div><br>
      <i class="fas fa-code" style="font-size: 48px; margin-right: 20px;"></i><div class="skill-container"><div id="python" class="skills" style="width: 94%"></div></div>
    </div>
    </section>
{% endblock views %}

ppw/templates/base.html
{% load static %}
<!doctype html>
<html>
  <head>
    <title>{{ title }}</title>
    {% block style %}
    {% endblock style %}
  </head>
  <body>
    {% block content %}
    <h1>this is base html,<br> You might forgot to change the content block.</h1>
    {% endblock content %}
  </body>
</html>